server.port=3000
spring.datasource.url=jdbc:postgresql://localhost:5432/db_taskmanager
spring.datasource.username=postgres
spring.datasource.password=14114
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true